//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRSWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAAssignments
    {
        public string TAAssignmentID { get; set; }
        public string TAID { get; set; }
        public string CourseID { get; set; }
        public string TermID { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual StudyTerms StudyTerms { get; set; }
        public virtual TAGraders TAGraders { get; set; }
    }
}
